# Generated by Django 2.1 on 2018-02-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('add_time', models.IntegerField()),
                ('last_time', models.IntegerField()),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
