# Generated by Django 2.1 on 2018-02-22 15:06

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('auther', models.CharField(max_length=30, verbose_name='作者')),
                ('brief', models.TextField(verbose_name='简要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='默认内容', verbose_name='内容')),
                ('cate_id', models.IntegerField(verbose_name='分类id')),
                ('source_name', models.CharField(max_length=50, verbose_name='来源网站名称')),
                ('source_url', models.CharField(max_length=50, verbose_name='来源网站url')),
                ('source_auther', models.CharField(max_length=30, verbose_name='来源网站作者')),
                ('type', models.IntegerField(verbose_name='转载或者原创')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('father_id', models.IntegerField(verbose_name='父级分类id')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30, verbose_name='评论内容')),
                ('article_id', models.IntegerField(verbose_name='文章id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('father_id', models.IntegerField(verbose_name='父级评论id')),
                ('add_time', models.IntegerField(verbose_name='添加时间')),
            ],
        ),
    ]
