# Generated by Django 2.1 on 2018-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180223_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.TextField(default='', verbose_name='简要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='简要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_auther',
            field=models.CharField(default='1', max_length=30, verbose_name='来源网站作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_name',
            field=models.CharField(default='', max_length=50, verbose_name='来源网站名称'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_url',
            field=models.CharField(default='', max_length=50, verbose_name='来源网站url'),
        ),
    ]
