# Generated by Django 2.1 on 2018-03-04 02:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180223_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=tinymce.models.HTMLField(verbose_name='简要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='文章详情'),
        ),
    ]
